name: cnn_first_break
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.0.1
  - python=3.12
  - pip:
      - monai==1.4.0
      - segysak==0.5.4
      - seispro==0.0.4
      - pandas==2.2.3
      - scikit-learn==1.6.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchmetrics==1.6.2
      - torchsummary==1.5.1
      - torchvision==0.21.0
      - pytorch-lightning==2.5.0.post0
